# Generated by Django 5.1.4 on 2025-02-25 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0005_alter_otp_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
