# Generated by Django 5.1.4 on 2025-03-29 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=15, unique=True)),
                ('discount', models.DecimalField(decimal_places=2, help_text='Discount amount or percentage', max_digits=5)),
                ('minimum_purchase', models.DecimalField(decimal_places=2, default=0, help_text='Minimum order amount required to apply coupon', max_digits=10)),
                ('maximum_discount', models.DecimalField(decimal_places=2, default=0, help_text='Maximum discount amount allowed for coupon', max_digits=10)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('status', models.BooleanField(default=True)),
                ('usage_limit', models.PositiveIntegerField(default=1, help_text='Total times this coupon can be used across users')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CouponUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used', models.BooleanField(default=False)),
                ('order_id', models.IntegerField(blank=True, help_text='Reference to the Order ID where this coupon was used', null=True)),
                ('redeemed_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupons.coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-redeemed_at'],
                'unique_together': {('user', 'coupon')},
            },
        ),
    ]
