# Generated by Django 5.1.4 on 2025-06-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponuser',
            name='order_id',
            field=models.CharField(blank=True, help_text='Reference to the Order ID where this coupon was used', max_length=100, null=True),
        ),
    ]
