# Generated by Django 5.1.4 on 2025-02-19 11:51

import category.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, default='no description', help_text='Optional, but should be at least 10 characters if provided.', validators=[django.core.validators.MinLengthValidator(10, 'Description must be at least 10 characters long.')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Only images up to 2MB are allowed.', null=True, upload_to='category_images/', validators=[category.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Category name should contain only letters and numbers.', max_length=100, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9\\s]+$', 'Only letters, numbers, and spaces are allowed.'), category.models.validate_no_leading_trailing_spaces]),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, help_text='Auto-generated from name if left blank.', max_length=120, unique=True),
        ),
    ]
