# Generated by Django 5.1.4 on 2025-06-13 05:37

import category.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_alter_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/', validators=[category.validators.validate_image_size, category.validators.validate_image_format]),
        ),
    ]
