# Generated by Django 5.1.4 on 2025-06-13 07:45

import category.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_alter_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='no image', upload_to='category_images/', validators=[category.validators.validate_image_size, category.validators.validate_image_format]),
            preserve_default=False,
        ),
    ]
