# Generated by Django 5.1.4 on 2025-03-13 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartitem_is_active_cartitem_variant_alter_cart_user'),
        ('products', '0021_productvariant_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='variant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='products.productvariant'),
        ),
    ]
