# Generated by Django 5.1.4 on 2025-04-08 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderaddress_remove_orderitem_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermain',
            name='payment_status',
            field=models.BooleanField(default=1),
        ),
    ]
