# Generated by Django 5.1.4 on 2025-04-09 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_ordermain_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermain',
            name='payment_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordermain',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
