# Generated by Django 5.1.4 on 2025-05-26 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_ordermain_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersub',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('ReturnReq', 'Return Requested'), ('Returned', 'Returned')], max_length=30, null=True),
        ),
    ]
