# Generated by Django 5.1.4 on 2025-01-27 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productimage_cropping'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
