# Generated by Django 5.1.4 on 2025-01-29 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='cropping',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
