# Generated by Django 5.1.4 on 2025-01-29 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_productimage_cropping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='cropping',
        ),
    ]
