# Generated by Django 5.1.4 on 2025-01-31 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_productimage_cropping'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='medium_image',
            field=models.ImageField(blank=True, upload_to='product_images/medium/'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='product_images/thumbnails/'),
        ),
    ]
