# Generated by Django 5.1.4 on 2025-01-31 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productimage_medium_image_productimage_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='medium_image',
        ),
    ]
