# Generated by Django 5.1.4 on 2025-02-01 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_productimage_medium_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='main_image',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='thumbnail',
        ),
    ]
