# Generated by Django 5.1.4 on 2025-02-06 10:08

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_product_main_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='detail_view',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.product_image_upload_path),
        ),
        migrations.AddField(
            model_name='productimage',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.product_image_upload_path),
        ),
        migrations.AddField(
            model_name='productimage',
            name='zoom_view',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.product_image_upload_path),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=products.models.product_image_upload_path),
        ),
    ]
