# Generated by Django 5.1.4 on 2025-02-07 08:16

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_productimage_detail_view_productimage_thumbnail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='variant',
            field=models.CharField(choices=[('original', 'Original'), ('thumbnail', 'Thumbnail'), ('detail', 'Detail View'), ('zoom', 'Zoom View')], default='original', max_length=20),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='detail_view',
            field=models.ImageField(blank=True, default='defaults/default_detail.jpg', null=True, upload_to=products.models.product_image_upload_path),

        ),
        migrations.AlterField(
            model_name='productimage',
            name='thumbnail',
            field=models.ImageField(blank=True, default='defaults/default_thumbnail.jpg', null=True, upload_to=products.models.product_image_upload_path),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='zoom_view',
            field=models.ImageField(blank=True, default='defaults/default_zoom_view.jpg', null=True, upload_to=products.models.product_image_upload_path),
        ),
    ]
