# Generated by Django 5.1.4 on 2025-02-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_productimage_variant_alter_productimage_detail_view_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='detail_view',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/details/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='zoom_view',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/zoom/'),
        ),
    ]
