# Generated by Django 5.1.4 on 2025-02-07 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_productimage_detail_view_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='detail_view',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='variant',
            field=models.CharField(choices=[('original', 'Original'), ('thumbnail', 'Thumbnail'), ('detail_view', 'Detail View'), ('zoom_view', 'Zoom View')], default='original', max_length=20),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='zoom_view',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
