# Generated by Django 5.1.4 on 2025-02-11 07:33

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_productimage_detail_view_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='detail_view',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='zoom_view',
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=products.models.product_image_upload_path),
        ),
    ]
