# Generated by Django 5.1.4 on 2025-02-12 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_productimage_detail_view_productimage_thumbnail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='detail_view',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='variant',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='zoom_view',
        ),
    ]
